# Generated by Django 4.1 on 2024-05-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_userfollowblock_userinblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threadvisibletouser",
            name="uid",
            field=models.ForeignKey(
                blank=True,
                db_column="uid",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="message.userscustomuser",
            ),
        ),
    ]
